Lmod has detected the following error: The following module(s) are unknown:
"cuda/12.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "cuda/12.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module



cuda available with GPU: Tesla V100-SXM2-16GB
[I] Loading dataset OGBG-MOLTOX21...
[I] Finished loading.
[I] Data load time: 2.7107s
MODEL DETAILS:

MODEL/Total parameters: GraphiT 1051852
[!] -LSPE: Initializing graph positional encoding with rand walk features.
[!] Time taken:  29.182235717773438
[!] -LSPE (For viz later): Adding lapeigvecs to key 'eigvec' for every graph.
[!] Time taken:  18.035320043563843
[!] Adding full graph connectivity..
Traceback (most recent call last):
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 509, in <module>
    main()
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 504, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs)
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 138, in train_val_pipeline
    dataset._make_full_graph() if MODEL_NAME == 'SAN' else dataset._make_full_graph((net_params['p_steps'], net_params['gamma']))
  File "/home/mikemont/final_project/gnn-lspe/data/ogb_mol.py", line 231, in _make_full_graph
    self.train = [make_full_graph(graph, adaptive_weighting) for graph in self.train]
  File "/home/mikemont/final_project/gnn-lspe/data/ogb_mol.py", line 231, in <listcomp>
    self.train = [make_full_graph(graph, adaptive_weighting) for graph in self.train]
  File "/home/mikemont/final_project/gnn-lspe/data/ogb_mol.py", line 121, in make_full_graph
    full_g.edges[g.edges(form='uv')[0].tolist(), g.edges(form='uv')[1].tolist()].data['feat'] = g.edata['feat']
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/view.py", line 227, in __setitem__
    self._graph._set_e_repr(self._etid, self._edges, {key: val})
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/heterograph.py", line 4441, in _set_e_repr
    eid = utils.parse_edges_arg_to_eid(self, edges, etid, "edges")
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/utils/checks.py", line 145, in parse_edges_arg_to_eid
    eid = g.edge_ids(u, v, etype=g.canonical_etypes[etid])
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/heterograph.py", line 3267, in edge_ids
    F.as_scalar(F.gather_row(u, idx)),
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py", line 57, in as_scalar
    return data.item()
RuntimeError: a Tensor with 32 elements cannot be converted to Scalar
